[tool.poetry]
name = "prospects-viewer"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.5"
arrow = "^0.12.1"
attrs = "*"
beautifulsoup4 = "^4.6"
click = "^6.7"
requests = "^2.18"

[tool.poetry.dev-dependencies]

